// src/components/Header.jsx
import React, {Component} from 'react';
import '../styles/header.css';
import { ReactComponent as Menu } from '../assets/menu.svg';
import { ReactComponent as Down } from '../assets/arrowdown.svg';
import Sidebar from '../components/Sidebar.jsx';

class Header extends Component {
  constructor(props) {
    super(props);
    this.state = {
      active: false
    };  
    // this.handleNav = this.handleNav.bind(this);
  }
  handleNav = () => {
    this.setState((prevState) => 
    {
      return { active: !prevState.active }
    });
  }
  render () {
    let sidebar;
    if(this.state.active) {
      sidebar = <Sidebar />
    }
    return (
      <div className="header bg-white lg:px-20">
        <div className="hidden md:block">
          <div className="grid grid-cols-3 pt-4"> 
            <div>
              <img src={require('../assets/Selendra.png')} alt="logo" className="w-12 h-12"/>
            </div>
            <div className="flex items-center">
              <span className="font-semibold flex items-center cursor-pointer">
                Company <Down/>
              </span>
              <span className="font-semibold flex items-center cursor-pointer ml-2">
                Digital Asset <Down/>
              </span>
              <span className="font-semibold flex items-center cursor-pointer ml-2">
                Product <Down/>
              </span>
            </div>
            <div className="flex">
              <button className="btn text-orange-600 w-32 block">Login</button>
              <button className="btn text-orange-600 lg:ml-2 w-32 border-orange-600 rounded-full md:border-2 hover:bg-orange-600 hover:text-white transition ease-in-out duration-500">Sign Up</button>
            </div>
          </div>
        </div>
        {/* mobile */}
        <div className="md:hidden">
          <div className="flex">
            <button onClick={this.handleNav}>
              <Menu />
            </button>
            <div className="flex justify-center w-full pt-4">
              <img src={require('../assets/Selendra.png')} alt="selendra" className="w-12 h-12 mr-8"/>
            </div>
          </div>
          { sidebar }
        </div>
      </div>
    )
  }
}

export default Header;

// components/Header.vue
<template>
  <div class="bg-white h-20 lg:px-20">
    <div class="hidden md:block">
      <div class="lg:grid grid-cols-3 pt-4 bg-white">
        <div class="flex justify-center">
          <img src="~/assets/Selendra.jpg" alt="selendra" class="w-12 mr-6">
        </div>
        <div class="flex items-center">
          <Product />
          <digital-asset class="lg:ml-4"/>
          <Company class="lg:ml-4"/>
        </div>
        <div class="flex justify-end">
          <button class="btn text-orange-600 w-32 block">Login</button>
          <button class="btn text-orange-600 lg:ml-2 w-32 border-orange-600 md:border-2 hover:bg-orange-600 hover:text-white transition ease-in-out duration-500">Sign Up</button>
        </div>
      </div>
    </div>
    <!-- mobile -->
    <div class="md:hidden">
      <div class="flex">
        <button @click="handleNav">
          <svg class="w-10 h-10" fill="currentColor" viewBox="0 0 20 20"><path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h6a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path></svg>
        </button>
        <div class="flex justify-center w-full pt-4">
          <img src="~/assets/Selendra.jpg" alt="selendra" class="w-12 mr-8">
        </div>
      </div>
      <div class="bg-white" :class="this.active === false ? 'block' : 'hidden' ">
        <ul class="px-4">
          <li class="btn flex justify-end">
            <a href="">Home</a> 
          </li>
          <li class="btn flex justify-end">
            <a href="">About</a>
          </li>
          <li class="btn flex justify-end">
            <a href="">Privacy & Policy</a>
          </li>
          <li class="btn flex justify-end">
            <a href="">Term Of Use</a>
          </li>
          <li class="btn flex justify-end">
            <a href="">Blog</a>
          </li>
          <li class="btn text-orange-500 flex justify-end">
            <a href="">LogIn</a>
          </li>
          <li class="btn text-orange-500 rounded  flex justify-end">
            <a href="">Sign Up</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</template>

<script>
import Product from '~/components/MegaMenu/Product';
import DigitalAsset from '~/components/MegaMenu/DigitalAsset';
import Company from '~/components/MegaMenu/Company';

export default {
  components: {
    Product,
    DigitalAsset,
    Company
  },
  data() {
    return {
      active: false
    }
  },
  methods: {
    handleNav() {
      this.active = !this.active;
    }
  }
}
</script>
